version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/
      dockerfile: nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./docker/
      - ./app:/var/www/html

  php:
    container_name: php
    build:
      context: ./docker/
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html