version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/
      dockerfile: nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./app:/app
  php:
    container_name: php
    build:
      context: ./docker/
      dockerfile: php.dockerfile
    volumes:
      - ./app:/app
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    # special config for linux
    env_file:
      - .env.docker